<?php
  namespace App\Http\Controllers;

  use Illuminate\Support\Facades\DB;

 function createSubAccount($bank, $nuban, $email, $name)
        {
            //create sub account;
            // Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
            $ch = curl_init();

                curl_setopt($ch, CURLOPT_URL, 'https://api.paystack.co/subaccount');
                curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
                curl_setopt($ch, CURLOPT_POST, 1);
                curl_setopt($ch, CURLOPT_POSTFIELDS,
                json_encode([
                  'business_name'=> $name,
                  'settlement_bank'=>"$bank",
                  'account_number'=> "$nuban",
                  'percentage_charge'=> 60.00,
                  'primary_contact_email'=> $email
                ]) );

                       $headers = array();
            $headers[] = 'Authorization: Bearer sk_test_d19851b5f833a45351489a7755a85a3b793b915d';
            $headers[] = 'Content-Type: application/json';
            curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

            $result = curl_exec($ch);
            if (curl_errno($ch)) {
                echo 'Error:' . curl_error($ch);
            }
            curl_close($ch);
            return json_decode($result,true);
            // echo $sub1['data']['subaccount_code'];
        }

 function getAccount($code, $acct)
            {
            //////resolve ACCOUNT///
            // Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
            $ch = curl_init();

            curl_setopt($ch, CURLOPT_URL, "https://api.paystack.co/bank/resolve?account_number={$acct}&bank_code={$code}");
            curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
            curl_setopt($ch, CURLOPT_CUSTOMREQUEST, 'GET');


            $headers = array();
            $headers[] = 'Authorization: Bearer sk_test_d19851b5f833a45351489a7755a85a3b793b915d';//sk_live_a158626d85329edd2b41caa8f0d1d7eca61d2d07
            curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

            $result = curl_exec($ch);
            if (curl_errno($ch)) {
                echo 'Error:' . curl_error($ch);
            }
            $bank = json_decode($result,true);
            if ($bank['status']) {
                echo $bank['data']['account_name'];
            }else {
              echo "ERR No Account found" ;
            }

            }

 function getBanks()
{
  // INIT

  // require __DIR__ . DIRECTORY_SEPARATOR . "lib" . DIRECTORY_SEPARATOR . "config.php";
  // require PATH_LIB . "database.php";
  $banks = DB::select('select name, code from paystack_bank');
  // $banks = new Users();
  // $banks = $banks->getBanks();

  // for ($i=0; $i < count($banks) ; $i++) {
  //   $name = $banks->  //$banks[$i]['name'];
  //   $code = $banks[$i]['code'];
  //   echo "<option value='$code'>$name</option>";
  // }
  foreach ($banks as $bank) {

    $name = $bank->name;  //$banks[$i]['name'];
    $code = $bank->code;  //$banks[$i]['code'];
    echo "<option value='$code'>$name</option>";
  }

}

 function updateSubAccount($value='')
{
////////update subaccount set active to false to delete/////
$ch = curl_init();

curl_setopt($ch, CURLOPT_URL, 'https://api.paystack.co/subaccount/ACCT_o0s0fhriikzefia');
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
curl_setopt($ch, CURLOPT_CUSTOMREQUEST, 'PUT');
curl_setopt($ch, CURLOPT_POSTFIELDS,
json_encode([
  'business_name'=>'olamide@ebis.com.ng Biztest',
  'settlement_bank'=>'035',
  'account_number'=> '0228664589',
  'percentage_charge'=> 40.00,
  'primary_contact_email'=>'olamide@ebis.com.ng',
  'active'=>true
]) );

$headers = array();
$headers[] = 'Authorization: Bearer SECRET_KEY';
$headers[] = 'Content-Type: application/json';
curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

$result = curl_exec($ch);
if (curl_errno($ch)) {
    echo 'Error:' . curl_error($ch);
}
curl_close($ch);
}


?>
